### ISSUE TITLE
Add DC and MODS to default DSID exclusion list

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/islandora_usage_stats_csv#2]
Like RELS_EXT and other DSIDs, MODS and DC datastream downloads would not be counted as object downloads by most people. They should be in the exclusion list by default.

**Comment by mjordan** [comment]
@bondjimbond thanks, wil do.

**Comment by mjordan** [comment]
Resolved with 4fa164def40332d23d09dd096c45d9a643ea6d6e.
