### ISSUE TITLE
Excluded DSIDs should also be excluded from aggregate download count

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/islandora_usage_stats_csv#3]
Currently this module counts all DSIDs downloads as object downloads, even RELS_EXT, MODS, DC, etc. Unwanted DSIDs should be excluded from the overall download count as well as from the breakdown of individual DSID downloads.

Suggestion: either (1) apply the exclusion list to both versions of the CSV, or (2) create a second exclusion list for the aggregate count.

**Comment by mjordan** [comment]
Thanks for catching this. I'll take a look.

**Comment by mjordan** [comment]
@bondjimbond I implemented your first suggestion. Can you test the issue-3 branch?

**Comment by bondjimbond** [comment]
Seems to work! Added DC,MODS to exclusion list. Before the pull, had about 27 downloads. After the pull, showed only 9.

**Comment by mjordan** [comment]
@bondjimbond thanks for testing. Resolved with a0fa30fc9073e6405ffc50a86be918ceddc98ae2.
